# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.launch_cluster_response import LaunchClusterResponse

class TestLaunchClusterResponse(unittest.TestCase):
    """LaunchClusterResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LaunchClusterResponse:
        """Test LaunchClusterResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LaunchClusterResponse`
        """
        model = LaunchClusterResponse()
        if include_optional:
            return LaunchClusterResponse(
                request_id = '',
                cluster_name = '',
                message = '',
                port_forward_info = {
                    'key' : null
                    }
            )
        else:
            return LaunchClusterResponse(
                request_id = '',
                cluster_name = '',
                message = '',
        )
        """

    def testLaunchClusterResponse(self):
        """Test LaunchClusterResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
