# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.organization_quota_response import OrganizationQuotaResponse

class TestOrganizationQuotaResponse(unittest.TestCase):
    """OrganizationQuotaResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationQuotaResponse:
        """Test OrganizationQuotaResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationQuotaResponse`
        """
        model = OrganizationQuotaResponse()
        if include_optional:
            return OrganizationQuotaResponse(
                organization_id = '',
                monthly_gpu_hours_per_user = 1.337,
                current_period_start = '',
                current_period_end = '',
                gpu_hours_used = 1.337,
                gpu_hours_remaining = 1.337,
                usage_percentage = 1.337
            )
        else:
            return OrganizationQuotaResponse(
                organization_id = '',
                monthly_gpu_hours_per_user = 1.337,
                current_period_start = '',
                current_period_end = '',
                gpu_hours_used = 1.337,
                gpu_hours_remaining = 1.337,
                usage_percentage = 1.337,
        )
        """

    def testOrganizationQuotaResponse(self):
        """Test OrganizationQuotaResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
