# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_usage_breakdown import UserUsageBreakdown

class TestUserUsageBreakdown(unittest.TestCase):
    """UserUsageBreakdown unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserUsageBreakdown:
        """Test UserUsageBreakdown
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserUsageBreakdown`
        """
        model = UserUsageBreakdown()
        if include_optional:
            return UserUsageBreakdown(
                user_id = '',
                user_email = '',
                user_name = '',
                gpu_hours_used = 1.337,
                gpu_hours_limit = 1.337,
                gpu_hours_remaining = 1.337,
                usage_percentage = 1.337
            )
        else:
            return UserUsageBreakdown(
                user_id = '',
                gpu_hours_used = 1.337,
                gpu_hours_limit = 1.337,
                gpu_hours_remaining = 1.337,
                usage_percentage = 1.337,
        )
        """

    def testUserUsageBreakdown(self):
        """Test UserUsageBreakdown"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
