# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.cluster_status_response import ClusterStatusResponse

class TestClusterStatusResponse(unittest.TestCase):
    """ClusterStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterStatusResponse:
        """Test ClusterStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterStatusResponse`
        """
        model = ClusterStatusResponse()
        if include_optional:
            return ClusterStatusResponse(
                cluster_name = '',
                status = '',
                launched_at = 56,
                last_use = '',
                autostop = 56,
                to_down = True,
                resources_str = '',
                user_info = {
                    'key' : null
                    }
            )
        else:
            return ClusterStatusResponse(
                cluster_name = '',
                status = '',
        )
        """

    def testClusterStatusResponse(self):
        """Test ClusterStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
