# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.quota_usage_response import QuotaUsageResponse

class TestQuotaUsageResponse(unittest.TestCase):
    """QuotaUsageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuotaUsageResponse:
        """Test QuotaUsageResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuotaUsageResponse`
        """
        model = QuotaUsageResponse()
        if include_optional:
            return QuotaUsageResponse(
                organization_quota = openapi_client.models.organization_quota_response.OrganizationQuotaResponse(
                    organization_id = '', 
                    monthly_gpu_hours_per_user = 1.337, 
                    current_period_start = '', 
                    current_period_end = '', 
                    gpu_hours_used = 1.337, 
                    gpu_hours_remaining = 1.337, 
                    usage_percentage = 1.337, ),
                recent_usage = [
                    openapi_client.models.gpu_usage_log_response.GPUUsageLogResponse(
                        id = '', 
                        organization_id = '', 
                        user_id = '', 
                        user_email = '', 
                        user_name = '', 
                        cluster_name = '', 
                        job_id = 56, 
                        gpu_count = 56, 
                        start_time = '', 
                        end_time = '', 
                        duration_hours = 1.337, 
                        instance_type = '', 
                        cloud_provider = '', 
                        cost_estimate = 1.337, )
                    ],
                total_usage_this_period = 1.337
            )
        else:
            return QuotaUsageResponse(
                organization_quota = openapi_client.models.organization_quota_response.OrganizationQuotaResponse(
                    organization_id = '', 
                    monthly_gpu_hours_per_user = 1.337, 
                    current_period_start = '', 
                    current_period_end = '', 
                    gpu_hours_used = 1.337, 
                    gpu_hours_remaining = 1.337, 
                    usage_percentage = 1.337, ),
                recent_usage = [
                    openapi_client.models.gpu_usage_log_response.GPUUsageLogResponse(
                        id = '', 
                        organization_id = '', 
                        user_id = '', 
                        user_email = '', 
                        user_name = '', 
                        cluster_name = '', 
                        job_id = 56, 
                        gpu_count = 56, 
                        start_time = '', 
                        end_time = '', 
                        duration_hours = 1.337, 
                        instance_type = '', 
                        cloud_provider = '', 
                        cost_estimate = 1.337, )
                    ],
                total_usage_this_period = 1.337,
        )
        """

    def testQuotaUsageResponse(self):
        """Test QuotaUsageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
