# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.job_record import JobRecord

class TestJobRecord(unittest.TestCase):
    """JobRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobRecord:
        """Test JobRecord
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobRecord`
        """
        model = JobRecord()
        if include_optional:
            return JobRecord(
                job_id = 56,
                job_name = '',
                username = '',
                submitted_at = 1.337,
                start_at = 1.337,
                end_at = 1.337,
                resources = '',
                status = '',
                log_path = ''
            )
        else:
            return JobRecord(
                job_id = 56,
                job_name = '',
                username = '',
                submitted_at = 1.337,
                resources = '',
                status = '',
                log_path = '',
        )
        """

    def testJobRecord(self):
        """Test JobRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
