# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.body_start_cli_authorization_api_v1_auth_cli_start_post import BodyStartCliAuthorizationApiV1AuthCliStartPost

class TestBodyStartCliAuthorizationApiV1AuthCliStartPost(unittest.TestCase):
    """BodyStartCliAuthorizationApiV1AuthCliStartPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyStartCliAuthorizationApiV1AuthCliStartPost:
        """Test BodyStartCliAuthorizationApiV1AuthCliStartPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyStartCliAuthorizationApiV1AuthCliStartPost`
        """
        model = BodyStartCliAuthorizationApiV1AuthCliStartPost()
        if include_optional:
            return BodyStartCliAuthorizationApiV1AuthCliStartPost(
                api_key = '',
                username = '',
                hostname = ''
            )
        else:
            return BodyStartCliAuthorizationApiV1AuthCliStartPost(
        )
        """

    def testBodyStartCliAuthorizationApiV1AuthCliStartPost(self):
        """Test BodyStartCliAuthorizationApiV1AuthCliStartPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
