# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_storage_bucket_request import CreateStorageBucketRequest

class TestCreateStorageBucketRequest(unittest.TestCase):
    """CreateStorageBucketRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateStorageBucketRequest:
        """Test CreateStorageBucketRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateStorageBucketRequest`
        """
        model = CreateStorageBucketRequest()
        if include_optional:
            return CreateStorageBucketRequest(
                name = '',
                remote_path = '',
                source = '',
                store = '',
                persistent = True,
                mode = 'MOUNT'
            )
        else:
            return CreateStorageBucketRequest(
                name = '',
                remote_path = '',
        )
        """

    def testCreateStorageBucketRequest(self):
        """Test CreateStorageBucketRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
