# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.body_authorize_cli_api_v1_auth_cli_authorize_post import BodyAuthorizeCliApiV1AuthCliAuthorizePost

class TestBodyAuthorizeCliApiV1AuthCliAuthorizePost(unittest.TestCase):
    """BodyAuthorizeCliApiV1AuthCliAuthorizePost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyAuthorizeCliApiV1AuthCliAuthorizePost:
        """Test BodyAuthorizeCliApiV1AuthCliAuthorizePost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyAuthorizeCliApiV1AuthCliAuthorizePost`
        """
        model = BodyAuthorizeCliApiV1AuthCliAuthorizePost()
        if include_optional:
            return BodyAuthorizeCliApiV1AuthCliAuthorizePost(
                session_id = '',
                authorized = True
            )
        else:
            return BodyAuthorizeCliApiV1AuthCliAuthorizePost(
                session_id = '',
                authorized = True,
        )
        """

    def testBodyAuthorizeCliApiV1AuthCliAuthorizePost(self):
        """Test BodyAuthorizeCliApiV1AuthCliAuthorizePost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
