# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.run_pod_test_request import RunPodTestRequest

class TestRunPodTestRequest(unittest.TestCase):
    """RunPodTestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunPodTestRequest:
        """Test RunPodTestRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunPodTestRequest`
        """
        model = RunPodTestRequest()
        if include_optional:
            return RunPodTestRequest(
                api_key = ''
            )
        else:
            return RunPodTestRequest(
                api_key = '',
        )
        """

    def testRunPodTestRequest(self):
        """Test RunPodTestRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
