# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.reports_response import ReportsResponse

class TestReportsResponse(unittest.TestCase):
    """ReportsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportsResponse:
        """Test ReportsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportsResponse`
        """
        model = ReportsResponse()
        if include_optional:
            return ReportsResponse(
                usage = [
                    openapi_client.models.report_data.ReportData(
                        date = '', 
                        value = 1.337, )
                    ],
                availability = [
                    openapi_client.models.report_data.ReportData(
                        date = '', 
                        value = 1.337, )
                    ],
                job_success = [
                    openapi_client.models.report_data.ReportData(
                        date = '', 
                        value = 1.337, )
                    ],
                total_jobs = 56,
                successful_jobs = 56,
                total_usage_hours = 1.337,
                average_availability_percent = 1.337
            )
        else:
            return ReportsResponse(
                usage = [
                    openapi_client.models.report_data.ReportData(
                        date = '', 
                        value = 1.337, )
                    ],
                availability = [
                    openapi_client.models.report_data.ReportData(
                        date = '', 
                        value = 1.337, )
                    ],
                job_success = [
                    openapi_client.models.report_data.ReportData(
                        date = '', 
                        value = 1.337, )
                    ],
                total_jobs = 56,
                successful_jobs = 56,
                total_usage_hours = 1.337,
                average_availability_percent = 1.337,
        )
        """

    def testReportsResponse(self):
        """Test ReportsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
