# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.cluster_response import ClusterResponse

class TestClusterResponse(unittest.TestCase):
    """ClusterResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterResponse:
        """Test ClusterResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterResponse`
        """
        model = ClusterResponse()
        if include_optional:
            return ClusterResponse(
                cluster_name = '',
                nodes = [
                    openapi_client.models.ssh_node.SSHNode(
                        ip = '', 
                        user = '', 
                        identity_file = '', 
                        password = '', 
                        resources = {
                            'key' : null
                            }, )
                    ]
            )
        else:
            return ClusterResponse(
                cluster_name = '',
                nodes = [
                    openapi_client.models.ssh_node.SSHNode(
                        ip = '', 
                        user = '', 
                        identity_file = '', 
                        password = '', 
                        resources = {
                            'key' : null
                            }, )
                    ],
        )
        """

    def testClusterResponse(self):
        """Test ClusterResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
