# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.organizations_response import OrganizationsResponse

class TestOrganizationsResponse(unittest.TestCase):
    """OrganizationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationsResponse:
        """Test OrganizationsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationsResponse`
        """
        model = OrganizationsResponse()
        if include_optional:
            return OrganizationsResponse(
                organizations = [
                    openapi_client.models.organization.Organization(
                        id = '', 
                        name = '', 
                        object = 'organization', )
                    ],
                current_organization_id = ''
            )
        else:
            return OrganizationsResponse(
                organizations = [
                    openapi_client.models.organization.Organization(
                        id = '', 
                        name = '', 
                        object = 'organization', )
                    ],
        )
        """

    def testOrganizationsResponse(self):
        """Test OrganizationsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
