# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_add_node_api_v1_clusters_cluster_name_nodes_post(self) -> None:
        """Test case for add_node_api_v1_clusters_cluster_name_nodes_post

        Add Node
        """
        pass

    def test_add_organization_member_api_v1_admin_orgs_organization_id_members_post(self) -> None:
        """Test case for add_organization_member_api_v1_admin_orgs_organization_id_members_post

        Add Organization Member
        """
        pass

    def test_auth_callback_api_v1_auth_callback_get(self) -> None:
        """Test case for auth_callback_api_v1_auth_callback_get

        Auth Callback
        """
        pass

    def test_cancel_cluster_job_api_v1_skypilot_jobs_cluster_name_job_id_cancel_post(self) -> None:
        """Test case for cancel_cluster_job_api_v1_skypilot_jobs_cluster_name_job_id_cancel_post

        Cancel Cluster Job
        """
        pass

    def test_check_auth_api_v1_auth_check_get(self) -> None:
        """Test case for check_auth_api_v1_auth_check_get

        Check Auth
        """
        pass

    def test_create_api_key_api_v1_api_keys_post(self) -> None:
        """Test case for create_api_key_api_v1_api_keys_post

        Create Api Key
        """
        pass

    def test_create_cluster_api_v1_clusters_post(self) -> None:
        """Test case for create_cluster_api_v1_clusters_post

        Create Cluster
        """
        pass

    def test_create_organization_api_v1_admin_orgs_post(self) -> None:
        """Test case for create_organization_api_v1_admin_orgs_post

        Create Organization
        """
        pass

    def test_delete_api_key_api_v1_api_keys_key_id_delete(self) -> None:
        """Test case for delete_api_key_api_v1_api_keys_key_id_delete

        Delete Api Key
        """
        pass

    def test_delete_azure_config_route_api_v1_skypilot_azure_config_config_key_delete(self) -> None:
        """Test case for delete_azure_config_route_api_v1_skypilot_azure_config_config_key_delete

        Delete Azure Config Route
        """
        pass

    def test_delete_cluster_api_v1_clusters_cluster_name_delete(self) -> None:
        """Test case for delete_cluster_api_v1_clusters_cluster_name_delete

        Delete Cluster
        """
        pass

    def test_delete_identity_file_api_v1_clusters_identity_files_file_path_delete(self) -> None:
        """Test case for delete_identity_file_api_v1_clusters_identity_files_file_path_delete

        Delete Identity File
        """
        pass

    def test_delete_organization_api_v1_admin_orgs_organization_id_delete(self) -> None:
        """Test case for delete_organization_api_v1_admin_orgs_organization_id_delete

        Delete Organization
        """
        pass

    def test_delete_runpod_config_route_api_v1_skypilot_runpod_config_config_key_delete(self) -> None:
        """Test case for delete_runpod_config_route_api_v1_skypilot_runpod_config_config_key_delete

        Delete Runpod Config Route
        """
        pass

    def test_down_skypilot_cluster_api_v1_skypilot_down_post(self) -> None:
        """Test case for down_skypilot_cluster_api_v1_skypilot_down_post

        Down Skypilot Cluster
        """
        pass

    def test_fetch_cluster_resources_api_v1_skypilot_fetch_resources_cluster_name_get(self) -> None:
        """Test case for fetch_cluster_resources_api_v1_skypilot_fetch_resources_cluster_name_get

        Fetch Cluster Resources
        """
        pass

    def test_get_active_port_forwards_api_v1_skypilot_port_forwards_get(self) -> None:
        """Test case for get_active_port_forwards_api_v1_skypilot_port_forwards_get

        Get Active Port Forwards
        """
        pass

    def test_get_all_cluster_platforms_api_v1_skypilot_cluster_platforms_get(self) -> None:
        """Test case for get_all_cluster_platforms_api_v1_skypilot_cluster_platforms_get

        Get All Cluster Platforms
        """
        pass

    def test_get_api_key_api_v1_api_keys_key_id_get(self) -> None:
        """Test case for get_api_key_api_v1_api_keys_key_id_get

        Get Api Key
        """
        pass

    def test_get_availability_reports_api_v1_reports_availability_get(self) -> None:
        """Test case for get_availability_reports_api_v1_reports_availability_get

        Get Availability Reports
        """
        pass

    def test_get_azure_config_actual_api_v1_skypilot_azure_config_actual_get(self) -> None:
        """Test case for get_azure_config_actual_api_v1_skypilot_azure_config_actual_get

        Get Azure Config Actual
        """
        pass

    def test_get_azure_config_api_v1_skypilot_azure_config_get(self) -> None:
        """Test case for get_azure_config_api_v1_skypilot_azure_config_get

        Get Azure Config
        """
        pass

    def test_get_azure_credentials_api_v1_skypilot_azure_credentials_get(self) -> None:
        """Test case for get_azure_credentials_api_v1_skypilot_azure_credentials_get

        Get Azure Credentials
        """
        pass

    def test_get_azure_instance_types_route_api_v1_skypilot_azure_instance_types_get(self) -> None:
        """Test case for get_azure_instance_types_route_api_v1_skypilot_azure_instance_types_get

        Get Azure Instance Types Route
        """
        pass

    def test_get_azure_instances_api_v1_skypilot_azure_instances_get(self) -> None:
        """Test case for get_azure_instances_api_v1_skypilot_azure_instances_get

        Get Azure Instances
        """
        pass

    def test_get_azure_regions_route_api_v1_skypilot_azure_regions_get(self) -> None:
        """Test case for get_azure_regions_route_api_v1_skypilot_azure_regions_get

        Get Azure Regions Route
        """
        pass

    def test_get_cluster_api_v1_clusters_cluster_name_get(self) -> None:
        """Test case for get_cluster_api_v1_clusters_cluster_name_get

        Get Cluster
        """
        pass

    def test_get_cluster_job_logs_api_v1_skypilot_jobs_cluster_name_job_id_logs_get(self) -> None:
        """Test case for get_cluster_job_logs_api_v1_skypilot_jobs_cluster_name_job_id_logs_get

        Get Cluster Job Logs
        """
        pass

    def test_get_cluster_jobs_api_v1_skypilot_jobs_cluster_name_get(self) -> None:
        """Test case for get_cluster_jobs_api_v1_skypilot_jobs_cluster_name_get

        Get Cluster Jobs
        """
        pass

    def test_get_cluster_platform_info_api_v1_skypilot_cluster_platform_cluster_name_get(self) -> None:
        """Test case for get_cluster_platform_info_api_v1_skypilot_cluster_platform_cluster_name_get

        Get Cluster Platform Info
        """
        pass

    def test_get_cluster_template_info_api_v1_skypilot_cluster_template_cluster_name_get(self) -> None:
        """Test case for get_cluster_template_info_api_v1_skypilot_cluster_template_cluster_name_get

        Get Cluster Template Info
        """
        pass

    def test_get_cluster_type_api_v1_skypilot_cluster_type_cluster_name_get(self) -> None:
        """Test case for get_cluster_type_api_v1_skypilot_cluster_type_cluster_name_get

        Get Cluster Type
        """
        pass

    def test_get_cost_report_api_v1_skypilot_cost_report_get(self) -> None:
        """Test case for get_cost_report_api_v1_skypilot_cost_report_get

        Get Cost Report
        """
        pass

    def test_get_current_user_info_api_v1_auth_me_get(self) -> None:
        """Test case for get_current_user_info_api_v1_auth_me_get

        Get Current User Info
        """
        pass

    def test_get_job_success_reports_api_v1_reports_job_success_get(self) -> None:
        """Test case for get_job_success_reports_api_v1_reports_job_success_get

        Get Job Success Reports
        """
        pass

    def test_get_login_url_api_v1_auth_login_url_get(self) -> None:
        """Test case for get_login_url_api_v1_auth_login_url_get

        Get Login Url
        """
        pass

    def test_get_node_pools_api_v1_node_pools_get(self) -> None:
        """Test case for get_node_pools_api_v1_node_pools_get

        Get Node Pools
        """
        pass

    def test_get_organization_api_v1_admin_orgs_organization_id_get(self) -> None:
        """Test case for get_organization_api_v1_admin_orgs_organization_id_get

        Get Organization
        """
        pass

    def test_get_past_job_logs_api_v1_skypilot_past_jobs_cluster_name_job_id_logs_get(self) -> None:
        """Test case for get_past_job_logs_api_v1_skypilot_past_jobs_cluster_name_job_id_logs_get

        Get Past Job Logs
        """
        pass

    def test_get_past_jobs_endpoint_api_v1_skypilot_past_jobs_get(self) -> None:
        """Test case for get_past_jobs_endpoint_api_v1_skypilot_past_jobs_get

        Get Past Jobs Endpoint
        """
        pass

    def test_get_runpod_config_api_v1_skypilot_runpod_config_get(self) -> None:
        """Test case for get_runpod_config_api_v1_skypilot_runpod_config_get

        Get Runpod Config
        """
        pass

    def test_get_runpod_display_options_route_api_v1_skypilot_runpod_display_options_get(self) -> None:
        """Test case for get_runpod_display_options_route_api_v1_skypilot_runpod_display_options_get

        Get Runpod Display Options Route
        """
        pass

    def test_get_runpod_display_options_with_pricing_route_api_v1_skypilot_runpod_display_options_with_pricing_get(self) -> None:
        """Test case for get_runpod_display_options_with_pricing_route_api_v1_skypilot_runpod_display_options_with_pricing_get

        Get Runpod Display Options With Pricing Route
        """
        pass

    def test_get_runpod_gpu_types_route_api_v1_skypilot_runpod_gpu_types_get(self) -> None:
        """Test case for get_runpod_gpu_types_route_api_v1_skypilot_runpod_gpu_types_get

        Get Runpod Gpu Types Route
        """
        pass

    def test_get_runpod_gpu_types_with_pricing_route_api_v1_skypilot_runpod_gpu_types_with_pricing_get(self) -> None:
        """Test case for get_runpod_gpu_types_with_pricing_route_api_v1_skypilot_runpod_gpu_types_with_pricing_get

        Get Runpod Gpu Types With Pricing Route
        """
        pass

    def test_get_runpod_instances_api_v1_skypilot_runpod_instances_get(self) -> None:
        """Test case for get_runpod_instances_api_v1_skypilot_runpod_instances_get

        Get Runpod Instances
        """
        pass

    def test_get_skypilot_cluster_status_api_v1_skypilot_status_get(self) -> None:
        """Test case for get_skypilot_cluster_status_api_v1_skypilot_status_get

        Get Skypilot Cluster Status
        """
        pass

    def test_get_skypilot_request_status_api_v1_skypilot_request_request_id_get(self) -> None:
        """Test case for get_skypilot_request_status_api_v1_skypilot_request_request_id_get

        Get Skypilot Request Status
        """
        pass

    def test_get_ssh_node_info_api_v1_skypilot_ssh_node_info_get(self) -> None:
        """Test case for get_ssh_node_info_api_v1_skypilot_ssh_node_info_get

        Get Ssh Node Info
        """
        pass

    def test_get_usage_reports_api_v1_reports_usage_get(self) -> None:
        """Test case for get_usage_reports_api_v1_reports_usage_get

        Get Usage Reports
        """
        pass

    def test_get_user_reports_api_v1_reports_get(self) -> None:
        """Test case for get_user_reports_api_v1_reports_get

        Get User Reports
        """
        pass

    def test_get_vscode_tunnel_info_endpoint_api_v1_skypilot_jobs_cluster_name_job_id_vscode_info_get(self) -> None:
        """Test case for get_vscode_tunnel_info_endpoint_api_v1_skypilot_jobs_cluster_name_job_id_vscode_info_get

        Get Vscode Tunnel Info Endpoint
        """
        pass

    def test_launch_skypilot_cluster_api_v1_skypilot_launch_post(self) -> None:
        """Test case for launch_skypilot_cluster_api_v1_skypilot_launch_post

        Launch Skypilot Cluster
        """
        pass

    def test_list_all_organizations_api_v1_admin_orgs_get(self) -> None:
        """Test case for list_all_organizations_api_v1_admin_orgs_get

        List All Organizations
        """
        pass

    def test_list_api_keys_api_v1_api_keys_get(self) -> None:
        """Test case for list_api_keys_api_v1_api_keys_get

        List Api Keys
        """
        pass

    def test_list_clusters_api_v1_clusters_get(self) -> None:
        """Test case for list_clusters_api_v1_clusters_get

        List Clusters
        """
        pass

    def test_list_identity_files_api_v1_clusters_identity_files_get(self) -> None:
        """Test case for list_identity_files_api_v1_clusters_identity_files_get

        List Identity Files
        """
        pass

    def test_list_node_pools_api_v1_skypilot_node_pools_get(self) -> None:
        """Test case for list_node_pools_api_v1_skypilot_node_pools_get

        List Node Pools
        """
        pass

    def test_list_organization_members_api_v1_admin_orgs_organization_id_members_get(self) -> None:
        """Test case for list_organization_members_api_v1_admin_orgs_organization_id_members_get

        List Organization Members
        """
        pass

    def test_list_ssh_clusters_api_v1_skypilot_ssh_clusters_get(self) -> None:
        """Test case for list_ssh_clusters_api_v1_skypilot_ssh_clusters_get

        List Ssh Clusters
        """
        pass

    def test_logout_api_v1_auth_logout_get(self) -> None:
        """Test case for logout_api_v1_auth_logout_get

        Logout
        """
        pass

    def test_refresh_session_api_v1_auth_refresh_post(self) -> None:
        """Test case for refresh_session_api_v1_auth_refresh_post

        Refresh Session
        """
        pass

    def test_regenerate_api_key_api_v1_api_keys_key_id_regenerate_post(self) -> None:
        """Test case for regenerate_api_key_api_v1_api_keys_key_id_regenerate_post

        Regenerate Api Key
        """
        pass

    def test_remove_node_api_v1_clusters_cluster_name_nodes_node_ip_delete(self) -> None:
        """Test case for remove_node_api_v1_clusters_cluster_name_nodes_node_ip_delete

        Remove Node
        """
        pass

    def test_remove_organization_member_api_v1_admin_orgs_organization_id_members_user_id_delete(self) -> None:
        """Test case for remove_organization_member_api_v1_admin_orgs_organization_id_members_user_id_delete

        Remove Organization Member
        """
        pass

    def test_rename_identity_file_route_api_v1_clusters_identity_files_file_path_put(self) -> None:
        """Test case for rename_identity_file_route_api_v1_clusters_identity_files_file_path_put

        Rename Identity File Route
        """
        pass

    def test_run_sky_check_azure_route_api_v1_skypilot_azure_sky_check_get(self) -> None:
        """Test case for run_sky_check_azure_route_api_v1_skypilot_azure_sky_check_get

        Run Sky Check Azure Route
        """
        pass

    def test_run_sky_check_runpod_route_api_v1_skypilot_runpod_sky_check_get(self) -> None:
        """Test case for run_sky_check_runpod_route_api_v1_skypilot_runpod_sky_check_get

        Run Sky Check Runpod Route
        """
        pass

    def test_save_azure_config_route_api_v1_skypilot_azure_config_post(self) -> None:
        """Test case for save_azure_config_route_api_v1_skypilot_azure_config_post

        Save Azure Config Route
        """
        pass

    def test_save_runpod_config_route_api_v1_skypilot_runpod_config_post(self) -> None:
        """Test case for save_runpod_config_route_api_v1_skypilot_runpod_config_post

        Save Runpod Config Route
        """
        pass

    def test_send_organization_invitation_api_v1_admin_orgs_organization_id_invitations_post(self) -> None:
        """Test case for send_organization_invitation_api_v1_admin_orgs_organization_id_invitations_post

        Send Organization Invitation
        """
        pass

    def test_serve_frontend_path_get(self) -> None:
        """Test case for serve_frontend_path_get

        Serve Frontend
        """
        pass

    def test_set_azure_default_config_route_api_v1_skypilot_azure_config_config_key_set_default_post(self) -> None:
        """Test case for set_azure_default_config_route_api_v1_skypilot_azure_config_config_key_set_default_post

        Set Azure Default Config Route
        """
        pass

    def test_set_runpod_default_config_route_api_v1_skypilot_runpod_config_config_key_set_default_post(self) -> None:
        """Test case for set_runpod_default_config_route_api_v1_skypilot_runpod_config_config_key_set_default_post

        Set Runpod Default Config Route
        """
        pass

    def test_setup_azure_api_v1_skypilot_azure_setup_get(self) -> None:
        """Test case for setup_azure_api_v1_skypilot_azure_setup_get

        Setup Azure
        """
        pass

    def test_setup_job_port_forward_api_v1_skypilot_jobs_cluster_name_job_id_setup_port_forward_post(self) -> None:
        """Test case for setup_job_port_forward_api_v1_skypilot_jobs_cluster_name_job_id_setup_port_forward_post

        Setup Job Port Forward
        """
        pass

    def test_setup_runpod_api_v1_skypilot_runpod_setup_get(self) -> None:
        """Test case for setup_runpod_api_v1_skypilot_runpod_setup_get

        Setup Runpod
        """
        pass

    def test_start_web_ssh_session_api_v1_skypilot_ssh_session_cluster_name_get(self) -> None:
        """Test case for start_web_ssh_session_api_v1_skypilot_ssh_session_cluster_name_get

        Start Web Ssh Session
        """
        pass

    def test_stop_port_forward_api_v1_skypilot_port_forwards_cluster_name_stop_post(self) -> None:
        """Test case for stop_port_forward_api_v1_skypilot_port_forwards_cluster_name_stop_post

        Stop Port Forward
        """
        pass

    def test_stop_skypilot_cluster_api_v1_skypilot_stop_post(self) -> None:
        """Test case for stop_skypilot_cluster_api_v1_skypilot_stop_post

        Stop Skypilot Cluster
        """
        pass

    def test_stream_skypilot_logs_api_v1_skypilot_stream_logs_logfile_get(self) -> None:
        """Test case for stream_skypilot_logs_api_v1_skypilot_stream_logs_logfile_get

        Stream Skypilot Logs
        """
        pass

    def test_submit_job_to_cluster_api_v1_skypilot_jobs_cluster_name_submit_post(self) -> None:
        """Test case for submit_job_to_cluster_api_v1_skypilot_jobs_cluster_name_submit_post

        Submit Job To Cluster
        """
        pass

    def test_terminal_connect_api_v1_terminal_get(self) -> None:
        """Test case for terminal_connect_api_v1_terminal_get

        Terminal Connect
        """
        pass

    def test_test_azure_connection_route_api_v1_skypilot_azure_test_post(self) -> None:
        """Test case for test_azure_connection_route_api_v1_skypilot_azure_test_post

        Test Azure Connection Route
        """
        pass

    def test_test_runpod_connection_route_api_v1_skypilot_runpod_test_post(self) -> None:
        """Test case for test_runpod_connection_route_api_v1_skypilot_runpod_test_post

        Test Runpod Connection Route
        """
        pass

    def test_update_api_key_api_v1_api_keys_key_id_put(self) -> None:
        """Test case for update_api_key_api_v1_api_keys_key_id_put

        Update Api Key
        """
        pass

    def test_update_member_role_api_v1_admin_orgs_organization_id_members_user_id_role_put(self) -> None:
        """Test case for update_member_role_api_v1_admin_orgs_organization_id_members_user_id_role_put

        Update Member Role
        """
        pass

    def test_upload_identity_file_api_v1_clusters_identity_files_post(self) -> None:
        """Test case for upload_identity_file_api_v1_clusters_identity_files_post

        Upload Identity File
        """
        pass

    def test_verify_azure_api_v1_skypilot_azure_verify_get(self) -> None:
        """Test case for verify_azure_api_v1_skypilot_azure_verify_get

        Verify Azure
        """
        pass

    def test_verify_runpod_api_v1_skypilot_runpod_verify_get(self) -> None:
        """Test case for verify_runpod_api_v1_skypilot_runpod_verify_get

        Verify Runpod
        """
        pass


if __name__ == '__main__':
    unittest.main()
