# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.storage_bucket_list_response import StorageBucketListResponse

class TestStorageBucketListResponse(unittest.TestCase):
    """StorageBucketListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StorageBucketListResponse:
        """Test StorageBucketListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StorageBucketListResponse`
        """
        model = StorageBucketListResponse()
        if include_optional:
            return StorageBucketListResponse(
                buckets = [
                    openapi_client.models.storage_bucket_response.StorageBucketResponse(
                        id = '', 
                        name = '', 
                        remote_path = '', 
                        source = '', 
                        store = '', 
                        persistent = True, 
                        mode = '', 
                        organization_id = '', 
                        created_by = '', 
                        created_at = '', 
                        updated_at = '', 
                        is_active = True, )
                    ],
                total_count = 56
            )
        else:
            return StorageBucketListResponse(
                buckets = [
                    openapi_client.models.storage_bucket_response.StorageBucketResponse(
                        id = '', 
                        name = '', 
                        remote_path = '', 
                        source = '', 
                        store = '', 
                        persistent = True, 
                        mode = '', 
                        organization_id = '', 
                        created_by = '', 
                        created_at = '', 
                        updated_at = '', 
                        is_active = True, )
                    ],
                total_count = 56,
        )
        """

    def testStorageBucketListResponse(self):
        """Test StorageBucketListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
