# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.stop_cluster_response import StopClusterResponse

class TestStopClusterResponse(unittest.TestCase):
    """StopClusterResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StopClusterResponse:
        """Test StopClusterResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StopClusterResponse`
        """
        model = StopClusterResponse()
        if include_optional:
            return StopClusterResponse(
                request_id = '',
                cluster_name = '',
                message = ''
            )
        else:
            return StopClusterResponse(
                request_id = '',
                cluster_name = '',
                message = '',
        )
        """

    def testStopClusterResponse(self):
        """Test StopClusterResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
