# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class OrganizationQuotaResponse(BaseModel):
    """
    OrganizationQuotaResponse
    """ # noqa: E501
    organization_id: StrictStr
    monthly_gpu_hours_per_user: Union[StrictFloat, StrictInt]
    current_period_start: StrictStr
    current_period_end: StrictStr
    gpu_hours_used: Union[StrictFloat, StrictInt]
    gpu_hours_remaining: Union[StrictFloat, StrictInt]
    usage_percentage: Union[StrictFloat, StrictInt]
    __properties: ClassVar[List[str]] = ["organization_id", "monthly_gpu_hours_per_user", "current_period_start", "current_period_end", "gpu_hours_used", "gpu_hours_remaining", "usage_percentage"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrganizationQuotaResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrganizationQuotaResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "organization_id": obj.get("organization_id"),
            "monthly_gpu_hours_per_user": obj.get("monthly_gpu_hours_per_user"),
            "current_period_start": obj.get("current_period_start"),
            "current_period_end": obj.get("current_period_end"),
            "gpu_hours_used": obj.get("gpu_hours_used"),
            "gpu_hours_remaining": obj.get("gpu_hours_remaining"),
            "usage_percentage": obj.get("usage_percentage")
        })
        return _obj


