# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from openapi_client.models.gpu_usage_log_response import GPUUsageLogResponse
from openapi_client.models.organization_quota_response import OrganizationQuotaResponse
from typing import Optional, Set
from typing_extensions import Self

class QuotaUsageResponse(BaseModel):
    """
    QuotaUsageResponse
    """ # noqa: E501
    organization_quota: OrganizationQuotaResponse
    recent_usage: List[GPUUsageLogResponse]
    total_usage_this_period: Union[StrictFloat, StrictInt]
    __properties: ClassVar[List[str]] = ["organization_quota", "recent_usage", "total_usage_this_period"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QuotaUsageResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of organization_quota
        if self.organization_quota:
            _dict['organization_quota'] = self.organization_quota.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in recent_usage (list)
        _items = []
        if self.recent_usage:
            for _item_recent_usage in self.recent_usage:
                if _item_recent_usage:
                    _items.append(_item_recent_usage.to_dict())
            _dict['recent_usage'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QuotaUsageResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "organization_quota": OrganizationQuotaResponse.from_dict(obj["organization_quota"]) if obj.get("organization_quota") is not None else None,
            "recent_usage": [GPUUsageLogResponse.from_dict(_item) for _item in obj["recent_usage"]] if obj.get("recent_usage") is not None else None,
            "total_usage_this_period": obj.get("total_usage_this_period")
        })
        return _obj


