# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.gpu_usage_log_response import GPUUsageLogResponse

class TestGPUUsageLogResponse(unittest.TestCase):
    """GPUUsageLogResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GPUUsageLogResponse:
        """Test GPUUsageLogResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GPUUsageLogResponse`
        """
        model = GPUUsageLogResponse()
        if include_optional:
            return GPUUsageLogResponse(
                id = '',
                organization_id = '',
                user_id = '',
                user_email = '',
                user_name = '',
                cluster_name = '',
                job_id = 56,
                gpu_count = 56,
                start_time = '',
                end_time = '',
                duration_hours = 1.337,
                instance_type = '',
                cloud_provider = '',
                cost_estimate = 1.337
            )
        else:
            return GPUUsageLogResponse(
                id = '',
                organization_id = '',
                user_id = '',
                cluster_name = '',
                gpu_count = 56,
                start_time = '',
        )
        """

    def testGPUUsageLogResponse(self):
        """Test GPUUsageLogResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
