# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_quota_response import UserQuotaResponse

class TestUserQuotaResponse(unittest.TestCase):
    """UserQuotaResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserQuotaResponse:
        """Test UserQuotaResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserQuotaResponse`
        """
        model = UserQuotaResponse()
        if include_optional:
            return UserQuotaResponse(
                user_id = '',
                user_email = '',
                user_name = '',
                organization_id = '',
                monthly_gpu_hours_per_user = 1.337,
                custom_quota = True,
                created_at = '',
                updated_at = ''
            )
        else:
            return UserQuotaResponse(
                user_id = '',
                organization_id = '',
                monthly_gpu_hours_per_user = 1.337,
                custom_quota = True,
                created_at = '',
                updated_at = '',
        )
        """

    def testUserQuotaResponse(self):
        """Test UserQuotaResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
