# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.status_response import StatusResponse

class TestStatusResponse(unittest.TestCase):
    """StatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatusResponse:
        """Test StatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatusResponse`
        """
        model = StatusResponse()
        if include_optional:
            return StatusResponse(
                clusters = [
                    openapi_client.models.cluster_status_response.ClusterStatusResponse(
                        cluster_name = '', 
                        status = '', 
                        launched_at = 56, 
                        last_use = '', 
                        autostop = 56, 
                        to_down = True, 
                        resources_str = '', 
                        user_info = {
                            'key' : null
                            }, )
                    ]
            )
        else:
            return StatusResponse(
                clusters = [
                    openapi_client.models.cluster_status_response.ClusterStatusResponse(
                        cluster_name = '', 
                        status = '', 
                        launched_at = 56, 
                        last_use = '', 
                        autostop = 56, 
                        to_down = True, 
                        resources_str = '', 
                        user_info = {
                            'key' : null
                            }, )
                    ],
        )
        """

    def testStatusResponse(self):
        """Test StatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
