"""hours to credits

Revision ID: 01b0bb95d722
Revises: 0efc3c29b9a7
Create Date: 2025-08-26 15:38:40.068792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b0bb95d722'
down_revision: Union[str, Sequence[str], None] = '0efc3c29b9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpu_usage_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_seconds', sa.Float(), nullable=True))
        batch_op.drop_column('duration_hours')

    with op.batch_alter_table('organization_quotas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_credits_per_user', sa.Float(), nullable=False))
        batch_op.drop_column('monthly_gpu_hours_per_user')

    with op.batch_alter_table('quota_periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits_used', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('credits_limit', sa.Float(), nullable=False))
        batch_op.drop_column('gpu_hours_used')
        batch_op.drop_column('gpu_hours_limit')

    with op.batch_alter_table('team_quotas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_credits_per_user', sa.Float(), nullable=False))
        batch_op.drop_column('monthly_gpu_hours_per_user')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_quotas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_gpu_hours_per_user', sa.FLOAT(), nullable=False))
        batch_op.drop_column('monthly_credits_per_user')

    with op.batch_alter_table('quota_periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gpu_hours_limit', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('gpu_hours_used', sa.FLOAT(), nullable=True))
        batch_op.drop_column('credits_limit')
        batch_op.drop_column('credits_used')

    with op.batch_alter_table('organization_quotas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_gpu_hours_per_user', sa.FLOAT(), nullable=False))
        batch_op.drop_column('monthly_credits_per_user')

    with op.batch_alter_table('gpu_usage_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_hours', sa.FLOAT(), nullable=True))
        batch_op.drop_column('duration_seconds')

    # ### end Alembic commands ###
