"""add_cluster_platforms_table

Revision ID: 11fc8dbff96c
Revises: 6aa5accea438
Create Date: 2025-08-22 10:41:29.520560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11fc8dbff96c'
down_revision: Union[str, Sequence[str], None] = '6aa5accea438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_platforms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cluster_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('template', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('user_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_name'),
    sa.UniqueConstraint('user_id', 'organization_id', 'display_name', name='uq_cluster_platforms_user_org_display')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cluster_platforms')
    # ### end Alembic commands ###
