"""allow_null_container_registry_id_for_standalone_images

Revision ID: 270d23c5a6bf
Revises: 1cf1b97fc266
Create Date: 2025-08-28 14:46:46.840156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '270d23c5a6bf'
down_revision: Union[str, Sequence[str], None] = '1cf1b97fc266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docker_images', schema=None) as batch_op:
        batch_op.alter_column('container_registry_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docker_images', schema=None) as batch_op:
        batch_op.alter_column('container_registry_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
