"""remove_template_add_state_to_cluster_platforms

Revision ID: 35a822c2e6c2
Revises: 37d8fdf0dd39
Create Date: 2025-08-28 13:30:11.123435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a822c2e6c2'
down_revision: Union[str, Sequence[str], None] = '37d8fdf0dd39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cluster_platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))
        batch_op.drop_column('template')

    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_team_memberships_org_user', ['organization_id', 'user_id'])

    with op.batch_alter_table('team_quotas', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_team_quotas_org_team', ['organization_id', 'team_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_quotas', schema=None) as batch_op:
        batch_op.drop_constraint('uq_team_quotas_org_team', type_='unique')

    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.drop_constraint('uq_team_memberships_org_user', type_='unique')

    with op.batch_alter_table('cluster_platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('state')

    # ### end Alembic commands ###
