"""f

Revision ID: 6540e0d327b3
Revises: add_org_id_to_ssh_keys
Create Date: 2025-08-26 09:06:32.185068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6540e0d327b3'
down_revision: Union[str, Sequence[str], None] = 'add_org_id_to_ssh_keys'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssh_keys', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssh_keys', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
