"""update_identity_files_to_org_level

Revision ID: 82dc2a90f155
Revises: 16024e62a7d1
Create Date: 2025-08-29 13:45:43.123221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82dc2a90f155'
down_revision: Union[str, Sequence[str], None] = '16024e62a7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_identity_files_org_user_name'), type_='unique')
        batch_op.create_unique_constraint('uq_identity_files_org_name', ['organization_id', 'display_name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_files', schema=None) as batch_op:
        batch_op.drop_constraint('uq_identity_files_org_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_identity_files_org_user_name'), ['organization_id', 'user_id', 'display_name'])

    # ### end Alembic commands ###
