"""add nodes JSON to ssh_node_pools and drop ssh_nodes

Revision ID: ba3ecb1d8950
Revises: e84717539e4c
Create Date: 2025-08-28 08:27:23.702928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ba3ecb1d8950'
down_revision: Union[str, Sequence[str], None] = 'e84717539e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ssh_nodes')
    with op.batch_alter_table('ssh_node_pools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nodes', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssh_node_pools', schema=None) as batch_op:
        batch_op.drop_column('nodes')

    op.create_table('ssh_nodes',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('pool_id', sa.VARCHAR(), nullable=False),
    sa.Column('ip', sa.VARCHAR(), nullable=False),
    sa.Column('user', sa.VARCHAR(), nullable=True),
    sa.Column('identity_file_path', sa.TEXT(), nullable=True),
    sa.Column('password', sa.TEXT(), nullable=True),
    sa.Column('resources', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['ssh_node_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
