"""Add allowed_team_ids to launch hooks

Revision ID: c6ea6baaf907
Revises: 7adc728854d2
Create Date: 2025-09-09 12:31:32.698585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ea6baaf907'
down_revision: Union[str, Sequence[str], None] = '7adc728854d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('launch_hooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_team_ids', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('launch_hooks', schema=None) as batch_op:
        batch_op.drop_column('allowed_team_ids')

    # ### end Alembic commands ###
