"""Add env_vars to launch_hooks

Revision ID: ca3f6e7fcc54
Revises: 08c1e27a5a83
Create Date: 2025-09-17 10:37:44.172300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3f6e7fcc54'
down_revision: Union[str, Sequence[str], None] = '08c1e27a5a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('launch_hooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('env_vars', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('launch_hooks', schema=None) as batch_op:
        batch_op.drop_column('env_vars')

    # ### end Alembic commands ###
