"""add user_id and organization_id to ssh_node_pools

Revision ID: e80ab25ad8a7
Revises: 6540e0d327b3
Create Date: 2025-08-26 10:54:05.261177

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e80ab25ad8a7"
down_revision: Union[str, Sequence[str], None] = "6540e0d327b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ssh_node_pools", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("organization_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("other_data", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ssh_node_pools", schema=None) as batch_op:
        batch_op.drop_column("other_data")
        batch_op.drop_column("organization_id")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
