"""add machine_size_templates

Revision ID: f5671b25e20c
Revises: c6ea6baaf907
Create Date: 2025-09-10 08:48:22.054135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5671b25e20c'
down_revision: Union[str, Sequence[str], None] = 'c6ea6baaf907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_size_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cloud_type', sa.String(), nullable=False),
    sa.Column('cloud_identifier', sa.String(), nullable=True),
    sa.Column('resources_json', sa.JSON(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'cloud_type', 'name', 'cloud_identifier', name='uq_mst_org_cloud_name_key')
    )
    with op.batch_alter_table('machine_size_templates', schema=None) as batch_op:
        batch_op.create_index('ix_mst_org_cloud', ['organization_id', 'cloud_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machine_size_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_mst_org_cloud')

    op.drop_table('machine_size_templates')
    # ### end Alembic commands ###
