"""add_user_quotas_and_modify_quota_periods

Revision ID: d51fd3166e33
Revises: f41ac9d5ce4f
Create Date: 2025-08-14 08:39:07.493508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d51fd3166e33"
down_revision: Union[str, Sequence[str], None] = "d7aec86e988a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Clear existing data since we're okay with losing it
    connection = op.get_bind()
    connection.execute(sa.text("DELETE FROM quota_periods"))

    # Add user_id column to quota_periods table if it doesn't exist
    inspector = sa.inspect(connection)
    columns = [col["name"] for col in inspector.get_columns("quota_periods")]
    if "user_id" not in columns:
        op.add_column("quota_periods", sa.Column("user_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quota_periods", "user_id")
    # ### end Alembic commands ###
