"""modify_organization_quotas_for_individual_users

Revision ID: d7aec86e988a
Revises: d51fd3166e33
Create Date: 2025-08-14 10:38:25.382946

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7aec86e988a"
down_revision: Union[str, Sequence[str], None] = "f41ac9d5ce4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the organization_quotas table with the new schema
    op.create_table(
        "organization_quotas",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("organization_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("monthly_gpu_hours_per_user", sa.Float(), nullable=False),
        sa.Column("custom_quota", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "user_id", name="uq_org_quotas_org_user"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organization_quotas")
    # ### end Alembic commands ###
