# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AzureConfigRequest(BaseModel):
    """
    AzureConfigRequest
    """ # noqa: E501
    name: StrictStr
    subscription_id: StrictStr
    tenant_id: StrictStr
    client_id: StrictStr
    client_secret: StrictStr
    allowed_instance_types: List[StrictStr]
    allowed_regions: List[StrictStr]
    max_instances: Optional[StrictInt] = 0
    config_key: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["name", "subscription_id", "tenant_id", "client_id", "client_secret", "allowed_instance_types", "allowed_regions", "max_instances", "config_key"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AzureConfigRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AzureConfigRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "subscription_id": obj.get("subscription_id"),
            "tenant_id": obj.get("tenant_id"),
            "client_id": obj.get("client_id"),
            "client_secret": obj.get("client_secret"),
            "allowed_instance_types": obj.get("allowed_instance_types"),
            "allowed_regions": obj.get("allowed_regions"),
            "max_instances": obj.get("max_instances") if obj.get("max_instances") is not None else 0,
            "config_key": obj.get("config_key")
        })
        return _obj


