# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SendInvitationRequest(BaseModel):
    """
    SendInvitationRequest
    """ # noqa: E501
    email: StrictStr
    organization_id: Optional[StrictStr] = None
    expires_in_days: Optional[StrictInt] = None
    inviter_user_id: Optional[StrictStr] = None
    role_slug: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["email", "organization_id", "expires_in_days", "inviter_user_id", "role_slug"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendInvitationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if organization_id (nullable) is None
        # and model_fields_set contains the field
        if self.organization_id is None and "organization_id" in self.model_fields_set:
            _dict['organization_id'] = None

        # set to None if expires_in_days (nullable) is None
        # and model_fields_set contains the field
        if self.expires_in_days is None and "expires_in_days" in self.model_fields_set:
            _dict['expires_in_days'] = None

        # set to None if inviter_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.inviter_user_id is None and "inviter_user_id" in self.model_fields_set:
            _dict['inviter_user_id'] = None

        # set to None if role_slug (nullable) is None
        # and model_fields_set contains the field
        if self.role_slug is None and "role_slug" in self.model_fields_set:
            _dict['role_slug'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendInvitationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "email": obj.get("email"),
            "organization_id": obj.get("organization_id"),
            "expires_in_days": obj.get("expires_in_days"),
            "inviter_user_id": obj.get("inviter_user_id"),
            "role_slug": obj.get("role_slug")
        })
        return _obj


