# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.team_list_response import TeamListResponse

class TestTeamListResponse(unittest.TestCase):
    """TeamListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamListResponse:
        """Test TeamListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamListResponse`
        """
        model = TeamListResponse()
        if include_optional:
            return TeamListResponse(
                teams = [
                    openapi_client.models.team_response.TeamResponse(
                        id = '', 
                        name = '', 
                        organization_id = '', 
                        created_by = '', 
                        created_at = '', 
                        updated_at = '', 
                        members = [
                            openapi_client.models.team_member_response.TeamMemberResponse(
                                user_id = '', 
                                email = '', 
                                first_name = '', 
                                last_name = '', 
                                profile_picture_url = '', )
                            ], )
                    ],
                total_count = 56
            )
        else:
            return TeamListResponse(
                teams = [
                    openapi_client.models.team_response.TeamResponse(
                        id = '', 
                        name = '', 
                        organization_id = '', 
                        created_by = '', 
                        created_at = '', 
                        updated_at = '', 
                        members = [
                            openapi_client.models.team_member_response.TeamMemberResponse(
                                user_id = '', 
                                email = '', 
                                first_name = '', 
                                last_name = '', 
                                profile_picture_url = '', )
                            ], )
                    ],
                total_count = 56,
        )
        """

    def testTeamListResponse(self):
        """Test TeamListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
