# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.job_logs_response import JobLogsResponse

class TestJobLogsResponse(unittest.TestCase):
    """JobLogsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobLogsResponse:
        """Test JobLogsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobLogsResponse`
        """
        model = JobLogsResponse()
        if include_optional:
            return JobLogsResponse(
                job_id = 56,
                logs = ''
            )
        else:
            return JobLogsResponse(
                job_id = 56,
                logs = '',
        )
        """

    def testJobLogsResponse(self):
        """Test JobLogsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
