# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.send_invitation_request import SendInvitationRequest

class TestSendInvitationRequest(unittest.TestCase):
    """SendInvitationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendInvitationRequest:
        """Test SendInvitationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendInvitationRequest`
        """
        model = SendInvitationRequest()
        if include_optional:
            return SendInvitationRequest(
                email = '',
                organization_id = '',
                expires_in_days = 56,
                inviter_user_id = '',
                role_slug = ''
            )
        else:
            return SendInvitationRequest(
                email = '',
        )
        """

    def testSendInvitationRequest(self):
        """Test SendInvitationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
