# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ssh_key_list_response import SSHKeyListResponse

class TestSSHKeyListResponse(unittest.TestCase):
    """SSHKeyListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SSHKeyListResponse:
        """Test SSHKeyListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SSHKeyListResponse`
        """
        model = SSHKeyListResponse()
        if include_optional:
            return SSHKeyListResponse(
                ssh_keys = [
                    openapi_client.models.ssh_key_response.SSHKeyResponse(
                        id = '', 
                        name = '', 
                        public_key = '', 
                        fingerprint = '', 
                        key_type = '', 
                        created_at = '', 
                        updated_at = '', 
                        last_used_at = '', 
                        is_active = True, )
                    ],
                total_count = 56
            )
        else:
            return SSHKeyListResponse(
                ssh_keys = [
                    openapi_client.models.ssh_key_response.SSHKeyResponse(
                        id = '', 
                        name = '', 
                        public_key = '', 
                        fingerprint = '', 
                        key_type = '', 
                        created_at = '', 
                        updated_at = '', 
                        last_used_at = '', 
                        is_active = True, )
                    ],
                total_count = 56,
        )
        """

    def testSSHKeyListResponse(self):
        """Test SSHKeyListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
