# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ssh_keys_api import SSHKeysApi


class TestSSHKeysApi(unittest.TestCase):
    """SSHKeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SSHKeysApi()

    def tearDown(self) -> None:
        pass

    def test_create_ssh_key_api_v1_ssh_keys_post(self) -> None:
        """Test case for create_ssh_key_api_v1_ssh_keys_post

        Create Ssh Key
        """
        pass

    def test_delete_ssh_key_api_v1_ssh_keys_key_id_delete(self) -> None:
        """Test case for delete_ssh_key_api_v1_ssh_keys_key_id_delete

        Delete Ssh Key
        """
        pass

    def test_get_ssh_key_api_v1_ssh_keys_key_id_get(self) -> None:
        """Test case for get_ssh_key_api_v1_ssh_keys_key_id_get

        Get Ssh Key
        """
        pass

    def test_list_ssh_keys_api_v1_ssh_keys_get(self) -> None:
        """Test case for list_ssh_keys_api_v1_ssh_keys_get

        List Ssh Keys
        """
        pass

    def test_lookup_user_by_ssh_key_api_v1_ssh_keys_lookup_by_key_get(self) -> None:
        """Test case for lookup_user_by_ssh_key_api_v1_ssh_keys_lookup_by_key_get

        Lookup User By Ssh Key
        """
        pass

    def test_update_ssh_key_api_v1_ssh_keys_key_id_put(self) -> None:
        """Test case for update_ssh_key_api_v1_ssh_keys_key_id_put

        Update Ssh Key
        """
        pass


if __name__ == '__main__':
    unittest.main()
