# coding: utf-8

"""
    Lattice

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.run_pod_config_request import RunPodConfigRequest

class TestRunPodConfigRequest(unittest.TestCase):
    """RunPodConfigRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunPodConfigRequest:
        """Test RunPodConfigRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunPodConfigRequest`
        """
        model = RunPodConfigRequest()
        if include_optional:
            return RunPodConfigRequest(
                name = '',
                api_key = '',
                allowed_gpu_types = [
                    ''
                    ],
                allowed_display_options = [
                    ''
                    ],
                max_instances = 56,
                config_key = ''
            )
        else:
            return RunPodConfigRequest(
                name = '',
                api_key = '',
                allowed_gpu_types = [
                    ''
                    ],
        )
        """

    def testRunPodConfigRequest(self):
        """Test RunPodConfigRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
